---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: code.pztrn.name/containers/mirror/plugins/docker:20.13.0
    settings:
      registry: code.pztrn.name
      username: drone
      password:
        from_secret: drone_secret
      repo: code.pztrn.name/containers/drone-nolimit
      auto_tag: true
